TOTAL_CAPITAL: 1000000
MAX_INVESTED: 900000
PER_TRADE_RISK: 1500    # smaller risk per trade to curb DD
SLIPPAGE: 0.001
FEE: 0.0003
MAX_POSITIONS: 3
SYMBOLS:
  - EXAMPLE.NS

# You can put this at top-level…
breakout_atr_buf: 0.25
atr_pct_max: 0.06
gap_guard_atr: 0.75
ext_cap_atr: 2.5
trail_lookback: 8
trail_atr_mult: 1.30
atr_pct_spike: 0.10
shock_atr_mult: 1.0
gap_atr_mult: 0.75

# …or nest them (either works)
# STRATEGY:
#   breakout_atr_buf: 0.25
#   atr_pct_max: 0.12
#   gap_guard_atr: 0.75
#   ext_cap_atr: 2.5
#   trail_lookback: 8
#   trail_atr_mult: 0.7
#   atr_pct_spike: 0.10
#   shock_atr_mult: 1.0
#   gap_atr_mult: 0.75

strategycfg:
  breakout_atr_buf: 0.25
  trail_atr_mult: 1.30
  atr_pct_max: 0.06












































